version: '3.6'
services:
  telegraf:
    image: telegraf:alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'
    networks:
      - backend

  influxdb:
    image: influxdb:alpine
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
      - elasticsearch
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - backend

  nodejs:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./nodejs-example:/usr/src/app
    ports:
       - "5050:5050"
    command: node example.js
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - backend


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend


  nginx:
    image: nginx:latest
    depends_on:
      - nodejs
    ports:
      - "80:80"
    volumes:
      - ./nginx-example/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-example/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend



volumes:
  grafana_data: {}
  influxdb_data: {}

networks:
  backend: